// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS-LuQkUyXz5m_CsHu0vSsK6byXW82bwY',
    appId: '1:608934583771:web:f093cdcdb2e2f11d771bfe',
    messagingSenderId: '608934583771',
    projectId: 'pick--em',
    authDomain: 'pick--em.firebaseapp.com',
    storageBucket: 'pick--em.firebasestorage.app',
    measurementId: 'G-0R6LX74QXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM4LWHcQwRnUxe10oBUqaFh9Byl4h-P5Q',
    appId: '1:608934583771:android:8efb98c1e962b305771bfe',
    messagingSenderId: '608934583771',
    projectId: 'pick--em',
    storageBucket: 'pick--em.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-tEKJU0b1y8WwGwuicoJJ1RZUYCmyPg',
    appId: '1:608934583771:ios:bb7e56e1d5860bbb771bfe',
    messagingSenderId: '608934583771',
    projectId: 'pick--em',
    storageBucket: 'pick--em.firebasestorage.app',
    iosBundleId: 'com.example.pickem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi-tEKJU0b1y8WwGwuicoJJ1RZUYCmyPg',
    appId: '1:608934583771:ios:bb7e56e1d5860bbb771bfe',
    messagingSenderId: '608934583771',
    projectId: 'pick--em',
    storageBucket: 'pick--em.firebasestorage.app',
    iosBundleId: 'com.example.pickem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS-LuQkUyXz5m_CsHu0vSsK6byXW82bwY',
    appId: '1:608934583771:web:cb1ac631a57670e2771bfe',
    messagingSenderId: '608934583771',
    projectId: 'pick--em',
    authDomain: 'pick--em.firebaseapp.com',
    storageBucket: 'pick--em.firebasestorage.app',
    measurementId: 'G-HFD3MP8FLT',
  );
}
